### ISSUE TITLE
More cabbages and bananas

### ISSUE THREAD

**Issue by kartikarora** [TheAndroidMaster/MonkeyTester#1]
I would like to give more cabbages and bananas by slight improvements in the UI and UX, and adding support for dear Namey McNameface (Nougat), if that's cool with the mighty goat!

**Comment by kartikarora** [comment]
Just to give an overview of what I have in mind
- Bump up the gradle plugin, sdk and build tools versions to support N (API 24)
- Change the text a little bit to make it more readable. Add github icon on toolbar. Add a visual indicator for moat or gokey, goat, monkey or nothing
- Change all `ACTION_VIEW` intents to chrome custom tabs to open the urls inside the app iteself, thus more cabbage time :stuck_out_tongue:

**Comment by fennifith** [comment]
Sounds good. I can do the first two if you want, but I've never used chrome custom tabs before :P
~~it's probably ridiculously easy I just don't feel like googling it~~

**Comment by kartikarora** [comment]
I have my bananas ready! 

I've already done the first two, except for the visual indicator!

I can send a PR in a few hours along with with the chrome tabs.
![device-2016-07-10-113800](https://cloud.githubusercontent.com/assets/6591617/16713555/bf3cacba-46c8-11e6-9a44-3a07c07e64ac.png)

**Comment by fennifith** [comment]
I just looked up the chrome custom tabs and it's ridiculously easy...
I'll add them once you make the PR

**Comment by kartikarora** [comment]
So you'll do the the custom tabs? I'll send the a PR right away if that's the case.

**Comment by fennifith** [comment]
Yep

**Comment by kartikarora** [comment]
4 commits in #2, have a look please!

**Comment by kartikarora** [comment]
Do you plan to update this on the PlayStore?

**Comment by fennifith** [comment]
Fixed with 0a77165. I'll update the play store version in a bit :P
For the 'visual indicator', I might ask if someone can make a few illustrations (or just make them myself) to set as a background to the collapsing toolbar.
